2025-07-31 22:26:12,530 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 22:26:14,088 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.start_latitude
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min 
FROM shifts 
WHERE shifts.start_time >= ? AND shifts.stop_time IS NULL]
[parameters: ('2025-07-31',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-31 22:26:23,776 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.start_latitude
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min 
FROM shifts 
WHERE shifts.start_time >= ? AND shifts.stop_time IS NULL]
[parameters: ('2025-07-31',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-31 22:26:31,353 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.start_latitude
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min 
FROM shifts 
WHERE shifts.start_time >= ? AND shifts.stop_time IS NULL]
[parameters: ('2025-07-31',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-07-31 22:36:32,765 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 22:41:52,347 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 22:52:32,603 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 23:05:22,364 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 23:16:47,584 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-07-31 23:26:51,074 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 07:04:05,153 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 07:22:56,753 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 07:41:00,083 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 08:14:21,368 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 08:24:14,388 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 08:47:09,757 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 09:03:40,762 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 09:05:11,765 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 09:11:19,711 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 14:05:03,231 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 14:05:04,789 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:05:08,175 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:05:10,027 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:05:12,267 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:05:28,085 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 14:05:29,741 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:40:18,084 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 14:40:19,690 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 14:45:54,316 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 14:45:55,885 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-01 15:36:19,835 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-01 15:36:21,585 - app - ERROR - B\u0142\u0105d podczas pobierania aktywnych pracowników: (sqlite3.OperationalError) no such column: shifts.status
[SQL: SELECT shifts.id AS shifts_id, shifts.employee_id AS shifts_employee_id, shifts.start_time AS shifts_start_time, shifts.stop_time AS shifts_stop_time, shifts.start_location AS shifts_start_location, shifts.stop_location AS shifts_stop_location, shifts.start_latitude AS shifts_start_latitude, shifts.start_longitude AS shifts_start_longitude, shifts.stop_latitude AS shifts_stop_latitude, shifts.stop_longitude AS shifts_stop_longitude, shifts.duration_min AS shifts_duration_min, shifts.status AS shifts_status, shifts.is_holiday AS shifts_is_holiday, shifts.is_sick AS shifts_is_sick 
FROM shifts 
WHERE shifts.stop_time IS NULL]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-08-02 09:46:07,164 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 09:57:43,537 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 12:23:42,214 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 13:13:42,142 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 15:54:31,904 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 16:10:19,264 - root - ERROR - B\u0142\u0105d podczas testu po\u0142\u0105czenia: type object 'datetime.datetime' has no attribute 'datetime'
2025-08-02 16:15:21,530 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 16:26:23,333 - root - ERROR - B\u0142\u0105d podczas aktualizacji konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:41:17,324 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:41:19,454 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 16:44:05,197 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:44:14,068 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:50:57,755 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:51:02,272 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 16:51:18,877 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 16:53:19,546 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 16:53:49,586 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 18:20:03,577 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 18:20:04,659 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 19:59:07,509 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 19:59:11,085 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 20:01:37,684 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:01:37,778 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:01:37,918 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:01:38,028 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:04:32,380 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:04:32,490 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:04:32,567 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:04:32,678 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:04:42,030 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:08:35,215 - root - ERROR - B\u0142\u0105d podczas generowania konfiguracji mobilnej: module 'datetime' has no attribute 'now'
2025-08-02 20:23:16,898 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 20:31:09,350 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 22:13:14,634 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 22:27:04,518 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-02 22:32:10,941 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 08:21:25,920 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 08:54:04,921 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\ptasz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 09:20:51,713 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 09:54:28,038 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 11:16:57,381 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 11:51:53,057 - root - WARNING - Próba aktualizacji konfiguracji bez uprawnie\u0144 administratora!
2025-08-03 11:53:53,596 - root - WARNING - Próba aktualizacji konfiguracji bez uprawnie\u0144 administratora!
2025-08-03 12:01:07,482 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 12:03:15,177 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 12:11:55,922 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 12:12:25,669 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 12:52:36,175 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 13:02:42,011 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 22:49:02,718 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-03 22:57:00,307 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 08:39:46,701 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 08:49:03,170 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 09:07:44,884 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 14:25:58,425 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 14:37:18,267 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 14:59:19,009 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-08-04 22:58:34,269 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "M:\Programowanie\lista_obecnosci\venv_new\lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
